---
- name: Disable swap
  command: swapoff -a

- name: Remove Swap entry from /etc/fstab.
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Get docker install script
  get_url:
    url: https://releases.rancher.com/install-docker/20.10.sh
    dest: /tmp/get-docker.sh
    mode: 0755

- name: Run docker install script
  shell: sh /tmp/get-docker.sh

- name: Install pre-requisites
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - ntp

- name: Setup kubemaster
  include_tasks: setup_kubemaster.yml
  when: "inventory_hostname == 'kubemaster'"