---
- name: Disable swap
  command: swapoff -a

- name: Remove Swap entry from /etc/fstab.
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Get docker install script
  get_url:
    url: https://releases.rancher.com/install-docker/20.10.sh
    dest: /tmp/get-docker.sh
    mode: 0755

- name: Run docker install script
  shell: sh /tmp/get-docker.sh

- name: Install pre-requisites
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - ntp

- name: Download the Google Cloud public signing key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    mode: 0644
  
- name: Add the Kubernetes apt repository
  shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: apt update
  apt:
    update_cache: yes
    
- name: Install kubectl
  apt: 
    name:
      - kubectl

- name: Download the Helm public signing key
  shell: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null

- name: Add the Helm apt repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

- name: apt update
  apt:
    update_cache: yes
    
- name: Install helm
  apt: 
    name:
      - helm