---
- name: Get docker install script
  get_url:
    url: https://releases.rancher.com/install-docker/20.10.sh
    dest: /tmp/get-docker.sh
    mode: 0755

- name: Run docker install script
  shell: sh /tmp/get-docker.sh
  become: yes